# Generated by Django 3.1.3 on 2022-07-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_like_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
